### ISSUE TITLE
NativeScript tns run android

### ISSUE THREAD

**Issue by giscafer** [giscafer/app-study#4]
### Problem

`Executing before-prepare hook from G:\000work_1ziton\HelloWorld\hooks\before-prepare\nativescript-dev-android-snapshot.js
Preparing project...
Unzipping C:\Users\giscafer\.gradle\wrapper\dists\gradle-2.10-bin\baigpnfu14tdk6ztbfwcl8275\gradle-2.10-bin.zip to C:\Users\giscafer\.gradle\wrapper\dists\gradle-2.10-bin\baigpnfu14tdk6ztbfwcl8275
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:159)
        at org.gradle.wrapper.Install.access$500(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:69)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Processing node_modules failed. Error: Command G:\000work_1ziton\HelloWorld\platforms\android\gradlew.bat failed with exit code 1`

Download a fresh gradle-2.10-bin.zip file and place it on the same folder as we deleted and try again to run your code : react-native run-android

It may work.You can download gradle zip file from the below Link: https://services.gradle.org/distributions

**Comment by giscafer** [comment]
###Problem

`processF0F1DebugResources`

路径不能有中文名称，文件命名也一样，必须规范。

maybe solve the problem

http://stackoverflow.com/questions/37695791/groceries-sample-app-end-branch-errors-out-during-compile

**Comment by giscafer** [comment]
**NativeScript does not have Node's module or its environment.**

https://github.com/NativeScript/NativeScript/issues/916

use file-system instead
http://docs.nativescript.org/cookbook/file-system
